name: Deploy to VPS
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          echo "🚀 Starting deployment..."
          
          # Debug - vérifier où on est
          echo "📍 Current directory: $(pwd)"
          echo "📂 Listing home directory:"
          ls -la ~/
          
          # Vérifier si le dossier existe
          if [ ! -d "$HOME/asmtariste/asmtariste__apt-user" ]; then
            echo "❌ Directory $HOME/asmtariste/asmtariste__apt-user does not exist!"
            exit 1
          fi
          
          # Aller dans le dossier du projet
          cd ~/asmtariste/asmtariste__apt-user
          echo "📍 Now in: $(pwd)"
          
          # Vérifier l'état Git avant
          echo "📝 Git status before pull:"
          git status
          echo "📝 Current branch:"
          git branch
          echo "📝 Last commit:"
          git log -1 --oneline
          
          # Forcer la mise à jour (écraser les modifications locales)
          #echo "📥 Resetting local changes and pulling..."
          #git reset --hard HEAD
          #git clean -fd
          git pull origin main
          
          # Vérifier l'état après
          echo "📝 Git status after pull:"
          git status
          echo "📝 New last commit:"
          git log -1 --oneline
          
          # Installer docker-compose si manquant
          echo "🐳 Checking docker-compose..."
          if ! command -v docker-compose &> /dev/null; then
            echo "Installing docker-compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi
          
          # Vérifier docker-compose dans le parent
          echo "🐳 Checking docker-compose file in parent directory:"
          ls -la ../docker-compose.yml || echo "⚠️ docker-compose.yml not found in parent!"
          
          # Arrêter les containers existants (depuis le parent)
          echo "🛑 Stopping containers..."
          cd .. && docker compose down || echo "⚠️ No containers to stop"
          
          # Rebuild et redémarrer (depuis le parent)
          echo "🔨 Building and starting containers..."
          docker compose up -d --build
          
          # Vérifier que tout fonctionne
          echo "✅ Checking containers status..."
          docker compose ps
          
          echo "🎉 Deployment completed!"